module ActiveRecord
  module Tablefree
    module ActsMethods
      module Version
        VERSION: String
      end
      VERSION: String
    end

    module Version
      VERSION: String
    end
    VERSION: String
    module NoDatabase
      module Version
        VERSION: String
      end
      VERSION: String
    end
  end
end
